// FIX: Se añadió "use client" para que el componente sea interactivo en el navegador.
"use client";

import React, { useState } from "react";

interface FaqItem {
  question: string;
  answer: string | { intro: string; steps: string[] };
}

const faqData: FaqItem[] = [
  {
    question: "What is E-invoicing?",
    answer:
      "E-invoicing, also known as electronic invoicing, is a system wherein B2B invoices are electronically authenticated by the GSTN/IRP portal of the Government of India.",
  },
  {
    question: "What is the e-invoice System?",
    answer:
      "The e-invoice system (electronic invoicing system) is a government-regulated framework introduced by the GST Council of India to standardize the way B2B invoices are reported. With Vyapar, this process becomes fully automated, error-free, and compliant.",
  },
  {
    question: "What Software is Best for E-invoices?",
    answer:
      "To generate various types of invoices online, e-invoicing software is used. It is mainly used in order to maintain records effectively. The best e-invoicing software in the market today is provided by Vyapar, offering multiple solutions and services for record-keeping and business management.",
  },
  {
    question: "How Can I Generate an E-invoice on Vyapar?",
    answer: {
      intro:
        "You can generate the e-invoice very quickly with Vyapar e-invoicing software. The following are the steps to generate an e-invoice. Make sure you don’t skip any particular steps.",
      steps: [
        "Click on ‘Add sale’ and update items & sale-quantity.",
        "Select a GST registered party.",
        "Click on ‘generate e-invoice’.",
        "Login using GSTIN, GSP username and Password (for the first time user).",
      ],
    },
  },
  {
    question: "What is The Difference Between Invoice and E-invoice?",
    answer:
      "The primary difference between an e-invoice and a simple invoice system is that a simple invoice mechanism applies to all taxpayers. In contrast, an e-invoice system applies to businesses with more than 5 crores annual turnover.",
  },
  {
    question: "What is an Invoice Reference Number (IRN)?",
    answer:
      "The Invoice Reference Number (IRN) is a unique identification number (also known as a hash) generated by the IRP under the e-invoicing system using a hash generation algorithm.",
  },
  {
    question: "Is it Mandatory to Generate The IRN?",
    answer:
      "Yes, generating IRN does hold some importance. Suppose a company meets the e-invoicing threshold but does not generate an e-invoice. In that case, i.e. the invoice does not include the official billing reference number from the IRP, the invoice is invalid.",
  },
  {
    question: "Does Vyapar Offer a Free Trial for its E-invoicing Software?",
    answer:
      "Yes, Vyapar provides a free trial that includes access to e-invoicing features. This allows users to explore the software’s functionality before committing to a paid plan.",
  },
  {
    question: "How Does Vyapar’s Pricing Compare to Other E-billing Software?",
    answer:
      "Vyapar offers a cost-effective solution for small and medium businesses. Its pricing is usually more affordable than some E-billing Software with many features. However, it still offers all the essential tools for GST compliance, invoicing, and financial management.",
  },
];

// Helper Component for the Star Rating
const StarRating = () => {
  const [rating, setRating] = useState(0);
  const [hover, setHover] = useState(0);

  return (
    <div className="mt-8 py-8 border-t border-gray-200">
      <h3 className="text-xl font-bold text-text-primary">
        How Useful Was This Post?
      </h3>
      <p className="text-sm text-text-secondary mt-1">
        Click on a star to rate it!
      </p>
      <div className="flex justify-center my-4">
        {[...Array(5)].map((_, index) => {
          const starValue = index + 1;
          return (
            <button
              key={starValue}
              type="button"
              className="text-4xl transition-colors"
              onClick={() => setRating(starValue)}
              onMouseEnter={() => setHover(starValue)}
              onMouseLeave={() => setHover(0)}
            >
              <span
                className={
                  starValue <= (hover || rating)
                    ? "text-yellow-400"
                    : "text-gray-300"
                }
              >
                &#9733;
              </span>
            </button>
          );
        })}
      </div>
      <p className="text-xs text-text-secondary">
        Average rating 4.41 / 5. Vote count: 440
      </p>
    </div>
  );
};

// Main Component
const FaqSection: React.FC = () => {
  return (
    <section className="bg-background-light py-16 md:py-24">
      <div className="container mx-auto px-4 max-w-4xl">
        {/* Top Promotional Banner */}
        <div className="text-center mb-12 p-4 rounded-lg bg-faq-accent">
          <h2 className="text-2xl font-bold text-primary-red">
            Take Your Business to the Next Level with Vyapar E-invoice System!
            Try FREE!
          </h2>
        </div>

        {/* Section Title */}
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-bold text-text-primary">
            Frequently Asked Questions (FAQs)
          </h2>
        </div>

        {/* FAQ List */}
        <div className="space-y-8">
          {faqData.map((item, index) => (
            <div key={index}>
              <h3 className="text-lg font-bold text-text-primary mb-2">
                {item.question}
              </h3>
              {typeof item.answer === "string" ? (
                <p className="text-text-secondary leading-relaxed">
                  {item.answer}
                </p>
              ) : (
                <div className="text-text-secondary leading-relaxed space-y-3">
                  <p>{item.answer.intro}</p>
                  <ol className="list-decimal list-inside space-y-1">
                    {item.answer.steps.map((step, stepIndex) => (
                      <li key={stepIndex}>{step}</li>
                    ))}
                  </ol>
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Star Rating Section */}
        <StarRating />
      </div>
    </section>
  );
};

export default FaqSection;
